GPU Particles
overte-org/overte-docs-sphinx pull request #51
Opened 2024-04-20 03:22 UTC by HifiExperiments

2024-11-02 04:13 UTC, HifiExperiments commented
this is ready for review now

2024-12-18 21:43 UTC, JulianGro approved these changes
Little suggestions.
Ready to merge, as long as the CI passes. (Which it does without my suggestions at least.)

2024-12-18 21:43 UTC, JulianGro commented on source/create/entities/procedural-particle-entity.rst
> +Particles are a powerful tool for creating a variety of effects. When you add a Particle Entity via **Create**, you will be asked if you want it to be procedural or not. Non-procedural particles are
```suggestion
Particles are a powerful tool for creating a variety of effects. When you add a Particle Entity via **Create**, you will be asked if you want it to be procedural or not. 

**Non-procedural particles** are represented by the `ParticleEffect` `EntityType <https://apidocs.overte.org/Entities.html#.EntityType>`_. They have many configuration options (see `EntityProperties-ParticleEffect <https://apidocs.overte.org/Entities.html#.EntityProperties-ParticleEffect>`_) and are suitable for many situations. However, they also have a few limitations, including only supporting up to 100,000 particles / entity, only allowing flat, billboarded, quads, and moving via euler integration (position + velocity + acceleration).
```

2024-12-18 21:43 UTC, JulianGro commented on source/create/entities/procedural-particle-entity.rst
> +If you instead create a procedural particle entity, you will get an entity with the `ProceduralParticleEffect` `EntityType <https://apidocs.overte.org/Entities.html#.EntityType>`_. This gives you fin
```suggestion
If you instead create a **procedural particle** entity, you will get an entity with the `ProceduralParticleEffect` `EntityType <https://apidocs.overte.org/Entities.html#.EntityType>`_. This gives you fine-grained control over a GPU particle system using procedural shaders for updating and rendering, plus higher per-system limits (up to millions of particles). Procedural particles have a different set of properties (see `EntityProperties-ProceduralParticleEffect <https://apidocs.overte.org/Entities.html#.EntityProperties-ProceduralParticleEffect>`_).
```

2024-12-18 21:43 UTC, JulianGro commented on source/create/entities/procedural-particle-entity.rst
> +``particleProps`` will contain as many update props as you specified. For example, if ``numUpdateProps == 3``, you'll have ``particleProps.prop0``, ``particleProps.prop1``, and ``particleProps.prop2`
```suggestion
``particleProps`` will contain as many update props as you specified. For example, if ``numUpdateProps == 3``, you'll have ``particleProps.prop0``, ``particleProps.prop1``, and ``particleProps.prop2``.
They will initially contain all 0s, and then will persist any values from previous frames. You can look up these properties during rendering (in both the vertex and fragment shaders) with:
```

2024-12-18 22:02 UTC, JulianGro requested changes
Actually, we should probably use GLSL syntax highlighting instead of JavaScript syntax highlighting.

2024-12-18 22:02 UTC, JulianGro commented on source/create/entities/procedural-particle-entity.rst
> +::
```suggestion
.. code-block:: glsl
```

2024-12-18 22:02 UTC, JulianGro commented on source/create/entities/procedural-particle-entity.rst
> +::
```suggestion
.. code-block:: glsl
```

2024-12-18 22:02 UTC, JulianGro commented on source/create/entities/procedural-particle-entity.rst
> +::
```suggestion
.. code-block:: glsl
```

2024-12-18 22:02 UTC, JulianGro commented on source/create/entities/procedural-particle-entity.rst
> +::
```suggestion
.. code-block:: glsl
```

2024-12-18 22:02 UTC, JulianGro commented on source/create/entities/procedural-particle-entity.rst
> +::
```suggestion
.. code-block:: glsl
```

2024-12-18 22:02 UTC, JulianGro commented on source/create/entities/procedural-particle-entity.rst
> +::
```suggestion
.. code-block:: glsl
```

2025-02-25 18:27 UTC, merged